version: '3.8'

networks:
  iot_network:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    networks:
      - iot_network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - iot_network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - iot_network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

  telegraf:
    image: telegraf:1.22
    container_name: telegraf
    networks:
      - iot_network
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt_broker
      - influxdb
    restart: always

volumes:
  influxdb-storage:
  grafana-storage:
